export const ActionType = {
    SET_PRODUCT : "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    FETCH_PRODUCT: "FETCH_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}

export const cartActionTypes = {
    SET_PRODUCT: "SET_PRODUCT",
    REMOVE_PRODUCT: "GET_PRODUCT"
}